# Установки

In [1]:
pip install unstructured\[pdf\]

Collecting unstructured[pdf]
  Downloading unstructured-0.18.31-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: charset-normalizer in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from unstructured[pdf]) (3.4.4)
Collecting filetype (from unstructured[pdf])
  Using cached filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting python-magic (from unstructured[pdf])
  Using cached python_magic-0.4.27-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting lxml (from unstructured[pdf])
  Downloading lxml-6.0.2-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.6 kB)
Collecting nltk (from unstructured[pdf])
  Downloading nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: requests in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from unstructured[pdf]) (2.32.5)
Requirement already satisfied: beautifulsoup4 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from unstructured[pdf]) (4.14.2)
Collecting emoji (from unstructured[pdf])
  Using cached emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting dataclasses-json (from unstructured[pdf])
  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting python-iso639 (from unstructured[pdf])
  Downloading python_iso639-2026.1.31-py3-none-any.whl.metadata (14 kB)
Collecting langdetect (from unstructured[pdf])
  Using cached langdetect-1.0.9.tar.gz (981 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from unstructured[pdf])
  Downloading numpy-2.4.2-cp311-cp311-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting rapidfuzz (from unstructured[pdf])
  Downloading rapidfuzz-3.14.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting backoff (from unstructured[pdf])
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: typing-extensions in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from unstructured[pdf]) (4.15.0)
Collecting unstructured-client (from unstructured[pdf])
  Using cached unstructured_client-0.42.8-py3-none-any.whl.metadata (23 kB)
Collecting wrapt (from unstructured[pdf])
  Downloading wrapt-2.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.4 kB)
Collecting tqdm (from unstructured[pdf])
  Downloading tqdm-4.67.2-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: psutil in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from unstructured[pdf]) (7.0.0)
Collecting python-oxmsg (from unstructured[pdf])
  Using cached python_oxmsg-0.0.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: html5lib in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from unstructured[pdf]) (1.1)
Collecting numba (from unstructured[pdf])
  Using cached numba-0.63.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.9 kB)
Collecting onnx>=1.17.0 (from unstructured[pdf])
  Downloading onnx-1.20.1-cp311-cp311-macosx_12_0_universal2.whl.metadata (8.4 kB)
Collecting onnxruntime>=1.19.0 (from unstructured[pdf])
  Using cached onnxruntime-1.23.2-cp311-cp311-macosx_13_0_arm64.whl.metadata (5.1 kB)
Collecting pdf2image (from unstructured[pdf])
  Using cached pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting pdfminer.six (from unstructured[pdf])
  Downloading pdfminer_six-20260107-py3-none-any.whl.metadata (4.3 kB)
Collecting pikepdf (from unstructured[pdf])
  Downloading pikepdf-10.3.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (8.4 kB)
Collecting pi_heif (from unstructured[pdf])
  Downloading pi_heif-1.2.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.5 kB)
Collecting pypdf (from unstructured[pdf])
  Using cached pypdf-6.6.2-py3-none-any.whl.metadata (7.1 kB)
Collecting google-cloud-vision (from unstructured[pdf])
  Using cached google_cloud_vision-3.12.0-py3-none-any.whl.metadata (9.8 kB)
Collecting effdet (from unstructured[pdf])
  Using cached effdet-0.4.1-py3-none-any.whl.metadata (33 kB)
Collecting unstructured-inference>=1.1.1 (from unstructured[pdf])
  Using cached unstructured_inference-1.2.0-py3-none-any.whl.metadata (5.5 kB)
Collecting unstructured.pytesseract>=0.3.12 (from unstructured[pdf])
  Using cached unstructured.pytesseract-0.3.15-py3-none-any.whl.metadata (11 kB)
Collecting protobuf>=4.25.1 (from onnx>=1.17.0->unstructured[pdf])
  Downloading protobuf-6.33.5-cp39-abi3-macosx_10_9_universal2.whl.metadata (593 bytes)
Collecting ml_dtypes>=0.5.0 (from onnx>=1.17.0->unstructured[pdf])
  Downloading ml_dtypes-0.5.4-cp311-cp311-macosx_10_9_universal2.whl.metadata (8.9 kB)
Collecting coloredlogs (from onnxruntime>=1.19.0->unstructured[pdf])
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime>=1.19.0->unstructured[pdf])
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: packaging in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from onnxruntime>=1.19.0->unstructured[pdf]) (25.0)
Collecting sympy (from onnxruntime>=1.19.0->unstructured[pdf])
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting python-multipart (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading python_multipart-0.0.22-py3-none-any.whl.metadata (1.8 kB)
Collecting huggingface-hub (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading huggingface_hub-1.3.7-py3-none-any.whl.metadata (13 kB)
Collecting opencv-python>=4.13.0.90 (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading opencv_python-4.13.0.90-cp37-abi3-macosx_13_0_arm64.whl.metadata (19 kB)
Collecting matplotlib (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading matplotlib-3.10.8-cp311-cp311-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting torch (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading torch-2.10.0-cp311-none-macosx_11_0_arm64.whl.metadata (31 kB)
Collecting timm (from unstructured-inference>=1.1.1->unstructured[pdf])
  Using cached timm-1.0.24-py3-none-any.whl.metadata (38 kB)
Collecting transformers>=4.25.1 (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading transformers-5.0.0-py3-none-any.whl.metadata (37 kB)
Collecting accelerate (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading accelerate-1.12.0-py3-none-any.whl.metadata (19 kB)
Collecting pandas (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading pandas-3.0.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting scipy (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading scipy-1.17.0-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting pypdfium2>=5.0.0 (from unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading pypdfium2-5.3.0-py3-none-macosx_11_0_arm64.whl.metadata (67 kB)
Collecting filelock (from transformers>=4.25.1->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading filelock-3.20.3-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: pyyaml>=5.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers>=4.25.1->unstructured-inference>=1.1.1->unstructured[pdf]) (6.0.3)
Collecting regex!=2019.12.17 (from transformers>=4.25.1->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading regex-2026.1.15-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers>=4.25.1->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.3 kB)
Collecting typer-slim (from transformers>=4.25.1->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading typer_slim-0.21.1-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.4.3 (from transformers>=4.25.1->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading fsspec-2026.1.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.2.0 (from huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading hf_xet-1.2.0-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (0.28.1)
Collecting shellingham (from huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: anyio in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (4.10.0)
Requirement already satisfied: certifi in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (1.0.9)
Requirement already satisfied: idna in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (0.16.0)
Collecting Pillow>=8.0.0 (from unstructured.pytesseract>=0.3.12->unstructured[pdf])
  Downloading pillow-12.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (8.8 kB)
Collecting networkx>=2.5.1 (from torch->unstructured-inference>=1.1.1->unstructured[pdf])
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: jinja2 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from torch->unstructured-inference>=1.1.1->unstructured[pdf]) (3.1.6)
Collecting mpmath<1.4,>=1.1.0 (from sympy->onnxruntime>=1.19.0->unstructured[pdf])
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: sniffio>=1.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub->unstructured-inference>=1.1.1->unstructured[pdf]) (1.3.1)
Requirement already satisfied: soupsieve>1.2 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from beautifulsoup4->unstructured[pdf]) (2.5)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.19.0->unstructured[pdf])
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->unstructured[pdf])
  Using cached marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json->unstructured[pdf])
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json->unstructured[pdf])
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting torchvision (from effdet->unstructured[pdf])
  Downloading torchvision-0.25.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.4 kB)
Collecting pycocotools>=2.0.2 (from effdet->unstructured[pdf])
  Downloading pycocotools-2.0.11-cp311-cp311-macosx_10_9_universal2.whl.metadata (1.3 kB)
Collecting omegaconf>=2.0 (from effdet->unstructured[pdf])
  Using cached omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf>=2.0->effdet->unstructured[pdf])
  Using cached antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision->unstructured[pdf])
  Using cached google_api_core-2.29.0-py3-none-any.whl.metadata (3.3 kB)
Collecting google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1 (from google-cloud-vision->unstructured[pdf])
  Using cached google_auth-2.48.0-py3-none-any.whl.metadata (6.2 kB)
Collecting grpcio<2.0.0,>=1.33.2 (from google-cloud-vision->unstructured[pdf])
  Downloading grpcio-1.76.0-cp311-cp311-macosx_11_0_universal2.whl.metadata (3.7 kB)
Collecting proto-plus<2.0.0,>=1.22.3 (from google-cloud-vision->unstructured[pdf])
  Using cached proto_plus-1.27.1-py3-none-any.whl.metadata (2.2 kB)
Collecting googleapis-common-protos<2.0.0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision->unstructured[pdf])
  Using cached googleapis_common_protos-1.72.0-py3-none-any.whl.metadata (9.4 kB)
Collecting grpcio-status<2.0.0,>=1.33.2 (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0,>=1.34.1->google-cloud-vision->unstructured[pdf])
  Using cached grpcio_status-1.76.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->unstructured[pdf])
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->unstructured[pdf])
  Downloading cryptography-46.0.4-cp311-abi3-macosx_10_9_universal2.whl.metadata (5.7 kB)
Collecting rsa<5,>=3.1.4 (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->unstructured[pdf])
  Using cached rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from requests->unstructured[pdf]) (2.6.3)
Collecting pyasn1>=0.1.3 (from rsa<5,>=3.1.4->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->unstructured[pdf])
  Downloading pyasn1-0.6.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: cffi>=2.0.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->unstructured[pdf]) (2.0.0)
Requirement already satisfied: pycparser in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=2.14.1->google-cloud-vision->unstructured[pdf]) (2.23)
Requirement already satisfied: six>=1.9 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from html5lib->unstructured[pdf]) (1.17.0)
Requirement already satisfied: webencodings in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from html5lib->unstructured[pdf]) (0.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from jinja2->torch->unstructured-inference>=1.1.1->unstructured[pdf]) (3.0.2)
Collecting contourpy>=1.0.1 (from matplotlib->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading contourpy-1.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->unstructured-inference>=1.1.1->unstructured[pdf])
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading fonttools-4.61.1-cp311-cp311-macosx_10_9_universal2.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading kiwisolver-1.4.9-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.3 kB)
Collecting pyparsing>=3 (from matplotlib->unstructured-inference>=1.1.1->unstructured[pdf])
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from matplotlib->unstructured-inference>=1.1.1->unstructured[pdf]) (2.9.0.post0)
Collecting click (from nltk->unstructured[pdf])
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Collecting joblib (from nltk->unstructured[pdf])
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting llvmlite<0.47,>=0.46.0dev0 (from numba->unstructured[pdf])
  Using cached llvmlite-0.46.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.0 kB)
Collecting numpy (from unstructured[pdf])
  Using cached numpy-2.3.5-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting Deprecated (from pikepdf->unstructured[pdf])
  Using cached deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting olefile (from python-oxmsg->unstructured[pdf])
  Downloading olefile-0.47-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting aiofiles>=24.1.0 (from unstructured-client->unstructured[pdf])
  Using cached aiofiles-25.1.0-py3-none-any.whl.metadata (6.3 kB)
Collecting pydantic>=2.11.2 (from unstructured-client->unstructured[pdf])
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting requests-toolbelt>=1.0.0 (from unstructured-client->unstructured[pdf])
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting annotated-types>=0.6.0 (from pydantic>=2.11.2->unstructured-client->unstructured[pdf])
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic>=2.11.2->unstructured-client->unstructured[pdf])
  Using cached pydantic_core-2.41.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic>=2.11.2->unstructured-client->unstructured[pdf])
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Downloading unstructured-0.18.31-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 6.4 MB/s  0:00:00m eta 0:00:01
Downloading onnx-1.20.1-cp311-cp311-macosx_12_0_universal2.whl (17.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.9/17.9 MB 3.3 MB/s  0:00:05m0:00:0100:01
Downloading ml_dtypes-0.5.4-cp311-cp311-macosx_10_9_universal2.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 505.6 kB/s  0:00:01eta 0:00:01
Using cached onnxruntime-1.23.2-cp311-cp311-macosx_13_0_arm64.whl (17.2 MB)
Downloading protobuf-6.33.5-cp39-abi3-macosx_10_9_universal2.whl (427 kB)
Using cached unstructured_inference-1.2.0-py3-none-any.whl (49 kB)
Downloading opencv_python-4.13.0.90-cp37-abi3-macosx_13_0_arm64.whl (46.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 MB 506.7 kB/s  0:01:24m0:00:0100:03
Downloading pypdfium2-5.3.0-py3-none-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 266.0 kB/s  0:00:11 eta 0:00:01
Downloading transformers-5.0.0-py3-none-any.whl (10.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 546.1 kB/s  0:00:18m0:00:010:01
Downloading huggingface_hub-1.3.7-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.7/536.7 kB 396.7 kB/s  0:00:01m-:--:--

In [20]:
pip install openai

Collecting openai
  Downloading openai-2.16.0-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from openai) (4.10.0)
Collecting distro<2,>=1.7.0 (from openai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from openai) (0.28.1)
Collecting jiter<1,>=0.10.0 (from openai)
  Downloading jiter-0.13.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.2 kB)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from openai) (2.12.5)
Requirement already satisfied: sniffio in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from openai) (4.67.2)
Requirement already satisfied: typing-extensions<5,>=4.11 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Downloading openai-2.16.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 5.1 MB/s  0:00:00 eta 0:00:01
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading jiter-0.13.0-cp311-cp311-macosx_11_0_arm64.whl (319 kB)
Installing collected packages: jiter, distro, openai
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [openai]2m2/3 [openai]
Successfully installed distro-1.9.0 jiter-0.13.0 openai-2.16.0
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install -q qdrant-client

Note: you may need to restart the kernel to use updated packages.

In [17]:
pip install chonkie

Collecting chonkie
  Downloading chonkie-1.5.4-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: tqdm>=4.64.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie) (4.67.2)
Requirement already satisfied: numpy>=2.0.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie) (2.3.5)
Collecting chonkie-core>=0.8.0 (from chonkie)
  Downloading chonkie_core-0.9.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting tenacity>=8.0.0 (from chonkie)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Downloading chonkie-1.5.4-py3-none-any.whl (209 kB)
Downloading chonkie_core-0.9.2-cp311-cp311-macosx_11_0_arm64.whl (336 kB)
Using cached tenacity-9.1.2-py3-none-any.whl (28 kB)
Installing collected packages: tenacity, chonkie-core, chonkie
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [chonkie]
Successfully installed chonkie-1.5.4 chonkie-core-0.9.2 tenacity-9.1.2
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip install "chonkie[semantic]"

Requirement already satisfied: chonkie[semantic] in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (1.5.4)
Requirement already satisfied: tqdm>=4.64.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie[semantic]) (4.67.2)
Requirement already satisfied: numpy>=2.0.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie[semantic]) (2.3.5)
Requirement already satisfied: chonkie-core>=0.8.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie[semantic]) (0.9.2)
Requirement already satisfied: tenacity>=8.0.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie[semantic]) (9.1.2)
Requirement already satisfied: tokenizers>=0.16.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from chonkie[semantic]) (0.22.2)
Collecting model2vec>=0.3.0 (from chonkie[semantic])
  Downloading model2vec-0.7.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: jinja2 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from model2vec>=0.3.0->chonkie[semantic]) (3.1.6)
Requirement already satisfied: joblib in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from model2vec>=0.3.0->chonkie[semantic]) (1.5.3)
Collecting rich (from model2vec>=0.3.0->chonkie[semantic])
  Downloading rich-14.3.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: safetensors in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from model2vec>=0.3.0->chonkie[semantic]) (0.7.0)
Requirement already satisfied: setuptools in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from model2vec>=0.3.0->chonkie[semantic]) (80.10.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from tokenizers>=0.16.0->chonkie[semantic]) (1.3.7)
Requirement already satisfied: filelock in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (2026.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (6.0.3)
Requirement already satisfied: shellingham in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (1.5.4)
Requirement already satisfied: typer-slim in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (4.15.0)
Requirement already satisfied: anyio in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (4.10.0)
Requirement already satisfied: certifi in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (1.0.9)
Requirement already satisfied: idna in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from jinja2->model2vec>=0.3.0->chonkie[semantic]) (3.0.2)
Collecting markdown-it-py>=2.2.0 (from rich->model2vec>=0.3.0->chonkie[semantic])
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from rich->model2vec>=0.3.0->chonkie[semantic]) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->model2vec>=0.3.0->chonkie[semantic])
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: click>=8.0.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from typer-slim->huggingface-hub<2.0,>=0.16.4->tokenizers>=0.16.0->chonkie[semantic]) (8.3.1)
Downloading model2vec-0.7.0-py3-none-any.whl (53 kB)
Downloading rich-14.3.2-py3-none-any.whl (309 kB)
Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: mdurl, markdown-it-py, rich, model2vec
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [model2vec]/4 [rich]
Successfully installed markdown-it-py-4.0.0 mdurl-0.1.2 model2vec-0.7.0 rich-14.3.2
Note: you may need to restart the kernel to use updated packages.

In [54]:
pip install pandas

Requirement already satisfied: pandas in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [72]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-macosx_12_0_arm64.whl (8.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.1/8.1 MB 314.0 kB/s  0:00:25 eta 0:00:01
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [scikit-learn][0m [scikit-learn]
Successfully installed scikit-learn-1.8.0 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [232]:
pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence_transformers-5.2.2-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (1.3.7)
Requirement already satisfied: torch>=1.11.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (2.10.0)
Requirement already satisfied: numpy in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (2.3.5)
Requirement already satisfied: scikit-learn in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (1.8.0)
Requirement already satisfied: scipy in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (1.17.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (4.15.0)
Requirement already satisfied: tqdm in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sentence_transformers) (4.67.2)
Requirement already satisfied: filelock in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (3.20.3)
Requirement already satisfied: packaging>=20.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.22.2)
Requirement already satisfied: typer-slim in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from transformers<6.0.0,>=4.41.0->sentence_transformers) (0.7.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2026.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (0.28.1)
Requirement already satisfied: shellingham in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.5.4)
Requirement already satisfied: anyio in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (4.10.0)
Requirement already satisfied: certifi in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (1.0.9)
Requirement already satisfied: idna in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from torch>=1.11.0->sentence_transformers) (3.6.1)
Requirement already satisfied: jinja2 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence_transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.2)
Requirement already satisfied: joblib>=1.3.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from scikit-learn->sentence_transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: click>=8.0.0 in /Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages (from typer-slim->transformers<6.0.0,>=4.41.0->sentence_transformers) (8.3.1)
Downloading sentence_transformers-5.2.2-py3-none-any.whl (494 kB)
Installing collected packages: sentence_transformers
Successfully installed sentence_transformers-5.2.2
Note: you may need to restart the kernel to use updated packages.

# Предподготовка

Для экспериментов были выбраны несколько игр и их дополнения

In [1]:
games_files = {
    "Дорога приключений": [
        "adventure road.pdf"
    ],
    "Бункер": [
        "bunker.pdf"
    ],
    "Каркассон": [
        "carcassonne.pdf"
    ],
    "Карточные войны": [
        "card wars.pdf"
    ],
    "Трамвай смерти": [
        "death tram.pdf"
    ],
    "Дюна: Империя": [
        "dune imperium_1.pdf",
        "dune imperium_2.pdf",
        "dune imperium_3.pdf",
        "dune imperium_4.pdf"
    ],
    "Взрывные котята": [
        "exploding kittens.pdf"
    ],
    "Игра престолов": [
        "got_1.pdf",
        "got_2.pdf",
        "motherofdragons.pdf"
    ],
    "Монополия Рик и Морти": [
        "monopoly.pdf"
    ]
}

games = ["Дорога приключений", "Бункер", "Каркассон", "Карточные войны",
         "Трамвай смерти", "Дюна: Империя", "Взрывные котята", "Игра престолов", "Монополия Рик и Морти"]

Используем unstructured для очистки и парсинга. Данная библиотека сама определяет тип текста (заголовок или просто текст), но делает это не всегда верно, поэтому будем делать это самостоятельно эвристически.

In [2]:
from unstructured.partition.pdf import partition_pdf

/Users/kapitolinakondakova/miniconda3/envs/rag/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Смотрим какие есть метаданные у данных фрагментов

In [3]:
path = f'files/got_1.pdf'
elements = partition_pdf(path)
elements[0].to_dict()

Warning: No languages specified, defaulting to English.

{'type': 'NarrativeText',
 'element_id': 'db33cc5c2939e2520691bab95126b698',
 'text': '«Железный трон мой по праву. Всякий, кто это отрицает, — мой враг». — Станнис Баратеон.',
 'metadata': {'coordinates': {'points': ((74.8069, 224.03300000000002),
    (74.8069, 242.04899999999998),
    (304.39329999999984, 242.04899999999998),
    (304.39329999999984, 224.03300000000002)),
   'system': 'PixelSpace',
   'layout_width': 609.449,
   'layout_height': 790.866},
  'file_directory': 'files',
  'filename': 'got_1.pdf',
  'last_modified': '2026-02-02T21:43:18',
  'page_number': 2,
  'languages': ['rus'],
  'filetype': 'application/pdf'}}

In [4]:
elements[0].__class__.__name__

'NarrativeText'

In [100]:
import os

API_KEY = os.environ.get('API_KEY')

### Функция для запросов к модели

In [6]:
from openai import OpenAI

client = OpenAI(
    base_url="https://api.polza.ai/api/v1",
    api_key=API_KEY,
)

def query(content, model="qwen/qwen3-next-80b-a3b-instruct") -> str:
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "user",
                "content": content,
            }
        ],
    )

    return completion.choices[0].message.content

### Подключаем Qdrant

In [7]:
from qdrant_client import QdrantClient

qclient = QdrantClient(
    url="http://localhost:6333"
)

qclient.get_collections()

CollectionsResponse(collections=[CollectionDescription(name='games_chunks_e5_small')])

# Подготовка данных, эксперименты с индексированием

Основная проблема pdf-файлов (в частности правил настольных игр), что у них нет одинаковой структуры и зачастую при парсинге даже та структура с разделами которая была может "съехать".

Так же при парсинге элементы могут идти не в правильном порядке (например, у нас две колонки, unstructured и другие пдф парсеры не всегда это считывают, поэтому прежде чем делить на чанки мы кластеризуем элементы по их горизонтальному положению на странице (то есть по x). Затем отсортируем сначала по номеру страницы, потом по кластеру, потом по y.

Для чанкирования мы попробуем несколько методов на бейзлайн модели, далее позже выберем несколько моделей эмбеддингов и посмотрим, что будет давать наилучший результат. 

Проводить тесты мы будем на таблице вопросов-ответов по данным настольным играм, ответами будут фрагменты из правил, которые отвечают на данный вопрос. Посмотрим на разные метрики (Hit@K и MRR). Так как при разных методах чанкирования фрагмент с ответом может иметь разные границы и формулировки, для оценки релевантности используется оценка того, насколько чанк покрыл правильный ответ.

Проверяемые методы:

1) Фиксированное разбиение
2) Разбиение по предложениям
3) Семантическое разбиение
4) Разбиение по структурным блокам

Первые три метода реализуем с помощью библиотеки Chonkie

4 способ будет реализован с помощью LLM и эмпирических правил. На первом этапе с помощью библиотеки unstructured выделяются строки, потенциально являющиеся заголовками. Поскольку данный инструмент может ошибочно классифицировать короткие строки как заголовки, на втором этапе эти кандидаты дополнительно проверяются языковой моделью, которая определяет, является ли строка логическим заголовком раздела. В случае положительного решения формируется новый чанк, включающий текст до следующего подтверждённого заголовка при условии соблюдения ограничений по длине.

Пока что на данном этапе ограничимся только названием игры в метаданных.

### Сортировка и кластеризация

In [8]:
class Element:
    def __init__(self, el):
        self.text = el.text
        self.x = (el.metadata.coordinates.points[0][0] + el.metadata.coordinates.points[1][0]) * 0.5
        self.y = (el.metadata.coordinates.points[0][1] + el.metadata.coordinates.points[1][1]) * 0.5
        self.page = el.metadata.page_number
        self.type = el.__class__.__name__
        self.cluster = 0

    def __str__(self):
        data = {
            "type": self.type,
            "page": self.page,
            "x": round(self.x, 2),
            "y": round(self.y, 2),
            "text": self.text[:100] + ("..." if len(self.text) > 100 else ""),
            "cluster": self.cluster
        }

        return "\n".join(f"{k}: {v}" for k, v in data.items())

In [9]:
from collections import defaultdict
games_texts_splitted = defaultdict(list)

for game_name in games:
    for file in games_files[game_name]:
        path = f'files/{file}'
        elements = partition_pdf(path)
        text_splitted = [Element(el) for el in elements if el.text]
        games_texts_splitted[game_name].append(text_splitted)

Warning: No languages specified, defaulting to English.

Cannot set non-stroke color because expected 4 components but got [1]

Warning: No languages specified, defaulting to English.

Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]
Cannot set non-stroke color because expected 4 components but got [1]

Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.
Warning: No languages specified, defaulting to English.

In [10]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

def estimate_eps(xs, k=5, q=90, min_eps=8.0, scale=1.2):
    """
    xs: array-like shape (n,1) или список x
    k: должен совпадать с min_samples
    q: перцентиль k-distance (чем выше, тем крупнее кластера)
    min_eps: нижняя граница eps в пикселях
    scale: дополнительный множитель (1.2-2.0 обычно)
    """
    xs = np.asarray(xs, dtype=float).reshape(-1, 1)

    nn = NearestNeighbors(n_neighbors=k)
    nn.fit(xs)
    distances, _ = nn.kneighbors(xs)

    k_dist = np.sort(distances[:, -1])  # расстояние до k-го соседа
    eps = np.percentile(k_dist, q) * scale

    return float(max(eps, min_eps))

In [11]:
def merge_close_clusters_by_x(page_elems, merge_thr=15.0):
    """
    Склеивает кластеры, если их центры по x ближе merge_thr пикселей.
    """
    clusters = sorted(set(e.cluster for e in page_elems))
    centers = {}
    sizes = {}
    for c in clusters:
        xs = [e.x for e in page_elems if e.cluster == c]
        centers[c] = float(np.mean(xs))
        sizes[c] = len(xs)

    ordered = sorted(clusters, key=lambda c: centers[c])

    mapping = {}
    new_id = 0
    mapping[ordered[0]] = 0
    prev = ordered[0]

    for c in ordered[1:]:
        if abs(centers[c] - centers[prev]) <= merge_thr:
            mapping[c] = new_id
        else:
            new_id += 1
            mapping[c] = new_id
            prev = c

    for e in page_elems:
        e.cluster = mapping[e.cluster]

In [12]:
from collections import defaultdict
import numpy as np
from sklearn.cluster import DBSCAN

def cluster_by_x_dbscan(elements, min_samples=5, q=90, eps_scale=1.5, eps_min=8.0, merge_thr=15.0):
    by_page = defaultdict(list)
    for e in elements:
        by_page[e.page].append(e)

    for page, page_elems in by_page.items():
        if len(page_elems) < min_samples:
            for e in page_elems:
                e.cluster = 0
            continue

        xs = np.array([[e.x] for e in page_elems], dtype=float)

        eps = estimate_eps(xs, k=min_samples, q=q, min_eps=eps_min, scale=eps_scale)

        db = DBSCAN(eps=eps, min_samples=min_samples)
        labels = db.fit_predict(xs)   # -1 = шум

        unique = sorted(set(labels))
        unique_no_noise = [u for u in unique if u != -1]

        if not unique_no_noise:
            for e in page_elems:
                e.cluster = 0
            continue

        centers = {lab: float(np.mean(xs[labels == lab])) for lab in unique_no_noise}
        ordered = sorted(unique_no_noise, key=lambda lab: centers[lab])

        remap = {lab: i for i, lab in enumerate(ordered)}
        noise_cluster = len(ordered)

        for e, lab in zip(page_elems, labels):
            e.cluster = remap.get(int(lab), noise_cluster)

        merge_close_clusters_by_x(page_elems, merge_thr=merge_thr)

        cur_clusters = sorted(set(e.cluster for e in page_elems))
        cur_centers = {}
        for c in cur_clusters:
            xs_c = [e.x for e in page_elems if e.cluster == c]
            cur_centers[c] = float(np.mean(xs_c))

        for e, lab in zip(page_elems, labels):
            if int(lab) != -1:
                continue
            nearest = min(cur_centers.keys(), key=lambda c: abs(e.x - cur_centers[c]))
            e.cluster = nearest

    return elements

In [13]:
from tqdm import tqdm

for game_name in tqdm(games, desc="Processing games"):
    for ind in range(len(games_texts_splitted[game_name])):
        cluster_by_x_dbscan(games_texts_splitted[game_name][ind])
        games_texts_splitted[game_name][ind] = sorted(
            games_texts_splitted[game_name][ind],
            key=lambda e: (e.page, e.cluster, e.y, e.x)
        )

Processing games: 100%|███████████████████████████| 9/9 [00:00<00:00, 61.74it/s]

Очистим от номеров страниц повторяющихся строк и т.д.

In [14]:
allowed_types = {"NarrativeText", "ListItem", "Title", "Text"}

def is_page_number(e):
    t = (e.text or "").strip()
    if t.isdigit():
        return True
    return False

def clean_elements(elements):
    allowed_types = {"NarrativeText", "ListItem", "Title", "Text"}

    seen = set()
    cleaned = []

    for e in elements:
        # 1. тип
        if e.type not in allowed_types:
            continue

        # 2. пустой текст
        if not e.text or not e.text.strip():
            continue

        # 3. номер страницы
        if is_page_number(e):
            continue

        # 4. дубликаты текста
        if e.text in seen:
            continue
        seen.add(e.text)

        cleaned.append(e)

    return cleaned

In [15]:
for game_name in tqdm(games, desc="Processing games"):
    for ind in range(len(games_texts_splitted[game_name])):
        games_texts_splitted[game_name][ind] = clean_elements(games_texts_splitted[game_name][ind])

Processing games: 100%|█████████████████████████| 9/9 [00:00<00:00, 4265.88it/s]

сэмпл

In [16]:
def print_elements(elements, n=5):
    for e in elements[:n]:
        print(e)
        print()

print_elements(games_texts_splitted["Игра престолов"][0], n=10)

type: NarrativeText
page: 2
x: 74.81
y: 233.04
text: «Железный трон мой по праву. Всякий, кто это отрицает, — мой враг». — Станнис Баратеон.
cluster: 0

type: NarrativeText
page: 2
x: 74.81
y: 278.08
text: «Вся страна это отрицает, брат. Старики отрицают это предсмертными хрипами, нерождённые дети отрицаю...
cluster: 0

type: Title
page: 2
x: 74.81
y: 323.12
text: «В игре престолов вы или побеждаете, или умираете». — Серсея Ланнистер.
cluster: 0

type: Title
page: 2
x: 82.08
y: 410.76
text: Настольная «Игра престолов», созданная на основе
cluster: 0

type: NarrativeText
page: 2
x: 72.0
y: 465.76
text: цикла романов Джорджа Мартина «Песнь льда и пламени», примет от трёх до шести игроков в мир эпически...
cluster: 0

type: NarrativeText
page: 2
x: 72.0
y: 586.81
text: В конце 10-го раунда игры победителем становится тот Дом, под властью которого находится наибольшее ...
cluster: 0

type: Title
page: 2
x: 90.82
y: 648.36
text: Количество игроков
cluster: 0

type: Title
page: 2
x: 90.67
y: 663.89
text: В «Игре престолов» могут сойтись от трёх до шести
cluster: 0

type: NarrativeText
page: 2
x: 80.59
y: 685.89
text: соперников. Если вы играете втроём, вчетвером или впятером, обратитесь к разделу «Неполный состав иг...
cluster: 0

type: Title
page: 2
x: 150.5
y: 388.89
text: ОБ ИГРЕ
cluster: 1

In [17]:
games_texts = defaultdict(list)

for game_name in games:
    for elements in games_texts_splitted[game_name]:
        games_texts[game_name].append("\n".join([el.text for el in elements]))

### Фиксированное разбиение

In [34]:
from chonkie import TokenChunker

# --- настройки ---
CHUNK_SIZE = 512
OVERLAP = 64
SAMPLE_N = 5

chunker = TokenChunker(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=OVERLAP
)

games_chunks_token = {}

for game_name in games_texts:
    games_chunks_token[game_name] = []
    for text in games_texts[game_name]:
        chunks = chunker.chunk(text)
        games_chunks_token[game_name].extend([ch.text for ch in chunks])

# --- вывод сэмпла ---
sample_game = next(iter(games_chunks_token.keys()))
sample_chunks = games_chunks_token[sample_game]

print(f"GAME: {sample_game}")
print(f"TOTAL CHUNKS: {len(sample_chunks)}")
print("-" * 80)

for i, ch in enumerate(sample_chunks[:SAMPLE_N], 1):
    preview = ch.replace("\n", " ")
    print(f"[Chunk {i}]")
    print(preview)
    print("-" * 80)

GAME: Дорога приключений
TOTAL CHUNKS: 69
--------------------------------------------------------------------------------
[Chunk 1]
Правила игры Безродный оруженосец становится легендарным рыцарем. Осиротевшая девочка занимает королевский трон, причитающийся ей по праву рождения. Дворянин, оплакивая трагически погибших родителей, становится благородным мстителем. Истории меняются, но мотивы вечны, как само время… А бесстрашные герои один за другим выходят на дорогу приключений! В игре «Дорога приключений» вы будете создавать собственных героев фэнтези-историй, сказок и баллад. Вы пройдете с ними путь от скромного происхождения до велико
--------------------------------------------------------------------------------
[Chunk 2]
ад. Вы пройдете с ними путь от скромного происхождения до великого предназначения, за это время они обретут уникальные черты, столкнутся со множеством испытаний и станут способными на настоящие подвиги. Каждый игрок получит своего героя с уникальной историей — но лишь одному суждено стать величайшим из них! Компоненты 45 карт персонажа 15 карт происхождения • 15 карт стремления • 15 карт судьбы 91 карта истории 29 карт I-го акта • 32 карты II-го акта • 30 карт III-го акта 50 карт героев и антигероев 25 карт
--------------------------------------------------------------------------------
[Chunk 3]
о акта • 30 карт III-го акта 50 карт героев и антигероев 25 карты героев • 25 карты антигероев 12 карт для одиночного и кооперативного режимов 40 фишек опыта 4 планшета персонажей и 4 маркера героев 24 руны 3 руны силы • 3 руны ловкости 3 руны телосложения 3 руны интеллекта • 3 руны мудрости 3 руны обаяния • 3 основных руны • 3 руны Тьмы Об игре Играя в «Дорогу приключений», вы пройдете три акта, полных испытаний и возможностей. Ваших героев ждут триумфы, трагедии и горечь поражений. Последние принесут с со
--------------------------------------------------------------------------------
[Chunk 4]
ут триумфы, трагедии и горечь поражений. Последние принесут с собой ценный опыт, распорядиться которым можно будет в будущих приключениях. С концом третьего акта игра завершится, а игрок, собравший больше всего очков судьбы, станет победителем! ) + Трагедия ( ) + Опыт ( ) = Судьба Триумф ( Перед тем как начать игру, найдите достаточно свободного места, разложите игровые компоненты и перемешайте колоды. На этапе подготовки каждый игрок создает своего персонажа. 1. Раздайте карты Раздайте каждому игроку по 6
--------------------------------------------------------------------------------
[Chunk 5]
воего персонажа. 1. Раздайте карты Раздайте каждому игроку по 6 карт персонажа: • 2 карты происхождения (коричневые с бронзовой оковкой). 2 карты стремления (синие с серебряной оковкой). 2 карты судьбы (красные с золотой оковкой). Игроки оставляют себе по одной карте каждого типа, а остальные возвращают в коробку. Если вы играете в первый раз, пропустите шаги выше и просто раздайте каждому игроку по одной карте каждого типа. Затем раздайте каждому игроку по три фишки опыта и одной карте героя, с которыми он
--------------------------------------------------------------------------------

### Разбиение по предложениям

In [35]:
from chonkie import SentenceChunker

# --- настройки ---
CHUNK_SIZE = 512
OVERLAP = 64
SAMPLE_N = 5

chunker = SentenceChunker(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=OVERLAP
)

games_chunks_sentence = {}

for game_name in games_texts:
    games_chunks_sentence[game_name] = []
    for text in games_texts[game_name]:
        chunks = chunker.chunk(text)
        games_chunks_sentence[game_name].extend([ch.text for ch in chunks])

# --- вывод сэмпла ---
sample_game = next(iter(games_chunks_sentence.keys()))
sample_chunks = games_chunks_sentence[sample_game]

print(f"GAME: {sample_game}")
print(f"TOTAL CHUNKS: {len(sample_chunks)}")
print("-" * 80)

for i, ch in enumerate(sample_chunks[:SAMPLE_N], 1):
    preview = ch.replace("\n", " ")
    print(f"[Chunk {i}]")
    print(preview)
    print("-" * 80)

GAME: Дорога приключений
TOTAL CHUNKS: 71
--------------------------------------------------------------------------------
[Chunk 1]
Правила игры Безродный оруженосец становится легендарным рыцарем. Осиротевшая девочка занимает королевский трон, причитающийся ей по праву рождения. Дворянин, оплакивая трагически погибших родителей, становится благородным мстителем. Истории меняются, но мотивы вечны, как само время… А бесстрашные герои один за другим выходят на дорогу приключений! В игре «Дорога приключений» вы будете создавать собственных героев фэнтези-историй, сказок и баллад.
--------------------------------------------------------------------------------
[Chunk 2]
Вы пройдете с ними путь от скромного происхождения до великого предназначения, за это время они обретут уникальные черты, столкнутся со множеством испытаний и станут способными на настоящие подвиги. Каждый игрок получит своего героя с уникальной историей — но лишь одному суждено стать величайшим из них! Компоненты 45 карт персонажа 15 карт происхождения • 15 карт стремления • 15 карт судьбы 91 карта истории 29 карт I-го акта • 32 карты II-го акта • 30 карт III-го акта
--------------------------------------------------------------------------------
[Chunk 3]
50 карт героев и антигероев 25 карты героев • 25 карты антигероев 12 карт для одиночного и кооперативного режимов 40 фишек опыта 4 планшета персонажей и 4 маркера героев 24 руны 3 руны силы • 3 руны ловкости 3 руны телосложения 3 руны интеллекта • 3 руны мудрости 3 руны обаяния • 3 основных руны • 3 руны Тьмы Об игре Играя в «Дорогу приключений», вы пройдете три акта, полных испытаний и возможностей. Ваших героев ждут триумфы, трагедии и горечь поражений.
--------------------------------------------------------------------------------
[Chunk 4]
Ваших героев ждут триумфы, трагедии и горечь поражений. Последние принесут с собой ценный опыт, распорядиться которым можно будет в будущих приключениях. С концом третьего акта игра завершится, а игрок, собравший больше всего очков судьбы, станет победителем! ) + Трагедия ( ) + Опыт ( ) = Судьба Триумф ( Перед тем как начать игру, найдите достаточно свободного места, разложите игровые компоненты и перемешайте колоды. На этапе подготовки каждый игрок создает своего персонажа. 1.
--------------------------------------------------------------------------------
[Chunk 5]
На этапе подготовки каждый игрок создает своего персонажа. 1. Раздайте карты Раздайте каждому игроку по 6 карт персонажа: • 2 карты происхождения (коричневые с бронзовой оковкой). 2 карты стремления (синие с серебряной оковкой). 2 карты судьбы (красные с золотой оковкой). Игроки оставляют себе по одной карте каждого типа, а остальные возвращают в коробку. Если вы играете в первый раз, пропустите шаги выше и просто раздайте каждому игроку по одной карте каждого типа.
--------------------------------------------------------------------------------

### Семантическое разбиение

Семантическое разбиение реализовано с использованием дефолтной embedding-модели, работающей локально, без обращения к внешним API.

In [37]:
from chonkie import SemanticChunker
from tqdm import tqdm

# --- настройки ---
EMB_MODEL = "minishlab/potion-base-32M"
THRESHOLD = 0.75
CHUNK_SIZE = 512
SIM_WINDOW = 3
SKIP_WINDOW = 0

SAMPLE_N = 5

chunker = SemanticChunker(
    embedding_model=EMB_MODEL,
    threshold=THRESHOLD,
    chunk_size=CHUNK_SIZE,
    similarity_window=SIM_WINDOW,
    skip_window=SKIP_WINDOW,
    min_sentences_per_chunk=2
)

games_chunks_semantic = {}

for game_name in tqdm(games_texts, desc="Chunking documents"):
    games_chunks_semantic[game_name] = []
    for text in games_texts[game_name]:
        chunks = chunker.chunk(text)
        games_chunks_semantic[game_name].extend([ch.text for ch in chunks])

# --- вывод сэмпла ---
sample_game = next(iter(games_chunks_semantic.keys()))
sample_chunks = games_chunks_semantic[sample_game]

print(f"GAME: {sample_game}")
print(f"TOTAL CHUNKS: {len(sample_chunks)}")
print("-" * 80)

for i, ch in enumerate(sample_chunks[:SAMPLE_N], 1):
    preview = ch.replace("\n", " ")
    print(f"[Chunk {i}]")
    print(preview)
    print("-" * 80)

Chunking documents: 100%|█████████████████████████| 9/9 [00:00<00:00, 16.20it/s]

GAME: Дорога приключений
TOTAL CHUNKS: 98
--------------------------------------------------------------------------------
[Chunk 1]
Правила игры Безродный оруженосец становится легендарным рыцарем. Осиротевшая девочка занимает королевский трон, причитающийся ей по праву рождения. Дворянин, оплакивая трагически погибших родителей, становится благородным мстителем. Истории меняются, но мотивы вечны, как само время… А бесстрашные герои один за другим выходят
--------------------------------------------------------------------------------
[Chunk 2]
на дорогу приключений! В игре «Дорога приключений» вы будете создавать собственных героев фэнтези-историй, сказок и баллад. Вы пройдете с ними путь от скромного происхождения до великого предназначения, за это время они обретут уникальные черты, столкнутся со множеством испытаний и станут способными на настоящие подвиги. Каждый игрок получит своего героя с уникальной историей — но лишь одному суждено стать величайшим из них! Компоненты
--------------------------------------------------------------------------------
[Chunk 3]
45 карт персонажа 15 карт происхождения • 15 карт стремления • 15 карт судьбы 91 карта истории 29 карт I-го акта • 32 карты II-го акта • 30 карт III-го акта
--------------------------------------------------------------------------------
[Chunk 4]
50 карт героев и антигероев 25 карты героев • 25 карты антигероев 12 карт для одиночного и кооперативного режимов 40 фишек опыта
--------------------------------------------------------------------------------
[Chunk 5]
4 планшета персонажей и 4 маркера героев 24 руны 3 руны силы • 3 руны ловкости 3 руны телосложения 3 руны интеллекта • 3 руны мудрости 3 руны обаяния • 3 основных руны • 3 руны Тьмы Об игре
--------------------------------------------------------------------------------

### Разбиение по структурным блокам

#### Определяем заголовки

In [21]:
import re

elements_for_check = []

BAD_TITLE_STARTS = {
    "и", "или", "а", "но", "что", "который", "которая", "которые",
    "это", "эти", "этот", "того", "также"
}

def _is_all_caps_ru(text: str) -> bool:
    letters = [ch for ch in text if ch.isalpha()]
    return bool(letters) and all(ch.isupper() for ch in letters)

def check_title(element):
    if element.type != "Title":
        return

    text = (element.text or "").strip()
    low = text.lower()

    if not text:
        element.type = "Text"
        return

    words = re.findall(r"\w+", low)
    n_words = len(words)

    if (
        text.endswith(".") or
        n_words >= 8 or
        (words and words[0] in BAD_TITLE_STARTS)
    ):
        element.type = "NarrativeText"
        return

    if _is_all_caps_ru(text) or text.endswith(":"):
        return

    elements_for_check.append(element)

In [22]:
import json

def parse_llm_json(raw: str):
    if not raw:
        return None
    a, b = raw.find("{"), raw.rfind("}")
    if a == -1 or b == -1 or b <= a:
        return None
    try:
        return json.loads(raw[a:b+1])
    except json.JSONDecodeError:
        return None

def llm_check(elements_for_check, batch_size=15, min_conf=0.60):
    """
    Ожидает JSON:
    {"results":[{"id":0,"type":"Title|NarrativeText|ListItem|Text","confidence":0.0}]}
    """

    allowed = {"Title", "NarrativeText", "ListItem", "Text"}
    id_elements = {i: e for i, e in enumerate(elements_for_check)}

    for start in tqdm(range(0, len(elements_for_check), batch_size), desc="Processing batches"):
        batch_ids = list(range(start, min(start + batch_size, len(elements_for_check))))
        items = [{"id": i, "text": (id_elements[i].text or "").strip()} for i in batch_ids]

        prompt = (
            "Ты классифицируешь фрагменты текста из PDF правил настольной игры.\n\n"
            "Для каждого элемента выбери ОДИН тип:\n"
            "- Title — заголовок раздела или подраздела. Примеры: Состав игры, Подготовка к игре\n"
            "- NarrativeText — обычный пояснительный текст\n"
            "- ListItem — пункт списка\n. Примеры: 1 маркер победных очков, Фишка персонажа"
            "- Text — прочее\n\n"
            "Ответь ТОЛЬКО валидным JSON без пояснений и Markdown.\n"
            "Формат ответа строго такой:\n"
            '{"results":[{"id":0,"type":"Title","confidence":0.95}]}\n'
            "Для каждого входного id должен быть ровно один результат.\n"
            "confidence от 0 до 1. Если не уверен — ставь < 0.6.\n\n"
            f"Входные данные:\n{json.dumps({'items': items}, ensure_ascii=False)}"
        )

        raw = query(prompt)
        data = parse_llm_json(raw)
        if not data or not isinstance(data.get("results"), list):
            continue
        for r in data["results"]:
            rid, rtype, conf = r.get("id"), r.get("type"), r.get("confidence")
            if rid in id_elements and rtype in allowed and isinstance(conf, (int, float)) and conf >= min_conf:
                id_elements[rid].type = rtype

In [23]:
for game_name in tqdm(games, desc="Processing games"):
    for elements in games_texts_splitted[game_name]:
        for el in elements:
            check_title(el)
len(elements_for_check)

Processing games: 100%|█████████████████████████| 9/9 [00:00<00:00, 2853.48it/s]

550

In [24]:
llm_check(elements_for_check)

Processing batches: 100%|███████████████████████| 37/37 [01:53<00:00,  3.06s/it]

#### Делим на чанки

In [25]:
import re
from chonkie import SentenceChunker

# --- настройки ---
CHUNK_SIZE_MAX = 512
OVERLAP = 64
SAMPLE_N = 10

chunker = SentenceChunker(
    chunk_size=CHUNK_SIZE_MAX,
    chunk_overlap=OVERLAP,
)

def is_garbage_title(text: str) -> bool:
    t = text.strip()
    if len(t) < 5:
        return True
    if sum(c.isalpha() for c in t) < 3:
        return True
    if t.endswith("(") or t.startswith(")"):
        return True
    if all(c in "()+-= " for c in t):
        return True
    return False

def build_chunks_from_docs(docs):
    chunks = []

    current_title = None
    current_body = []

    def flush():
        nonlocal current_title, current_body
        if current_title is None:
            return

        raw_title = (current_title.text or "").strip()
        title_text = "" if is_garbage_title(raw_title) else raw_title

        body_text = "\n".join(
            (e.text or "").strip()
            for e in current_body
            if (e.text or "").strip()
        )
        
        if not body_text:
            if title_text:
                chunks.append(title_text)
            return
        else:
            if title_text:
                full_text = f"{title_text}\n{body_text}"
            else:
                full_text = body_text

            if len(chunker.tokenizer.encode(full_text)) <= CHUNK_SIZE_MAX:
                chunks.append(full_text)
            else:
                body_chunks = chunker.chunk(body_text)
                for part in body_chunks:
                    if title_text:
                        chunks.append(f"{title_text}\n{part.text}")
                    else:
                        chunks.append(part.text)


        current_title = None
        current_body = []

    for page in docs:
        for e in page:
            if e.type == "Title":
                flush()
                current_title = e
            else:
                if current_title is not None:
                    current_body.append(e)

    flush()
    return chunks

In [26]:
from tqdm import tqdm

games_chunks_structure = {}

for game, docs in tqdm(games_texts_splitted.items()):
    games_chunks_structure[game] = build_chunks_from_docs(docs)


# --- вывод сэмпла ---
sample_game = next(iter(games_chunks_structure.keys()))
sample_chunks = games_chunks_structure[sample_game]

print(f"GAME: {sample_game}")
print(f"TOTAL CHUNKS: {len(sample_chunks)}")
print("-" * 80)

for i, ch in enumerate(sample_chunks[:SAMPLE_N], 1):
    preview = ch.replace("\n", " ")
    print(f"[Chunk {i}]")
    print(preview)
    print("-" * 80)

100%|████████████████████████████████████████████| 9/9 [00:00<00:00, 271.33it/s]

GAME: Дорога приключений
TOTAL CHUNKS: 80
--------------------------------------------------------------------------------
[Chunk 1]
Правила игры Безродный оруженосец становится легендарным рыцарем. Осиротевшая девочка занимает королевский трон, причитающийся ей по праву рождения. Дворянин, оплакивая трагически погибших родителей, становится благородным мстителем. Истории меняются, но мотивы вечны, как само время… А бесстрашные герои один за другим выходят
--------------------------------------------------------------------------------
[Chunk 2]
на дорогу приключений! В игре «Дорога приключений» вы будете создавать собственных героев фэнтези-историй, сказок и баллад. Вы пройдете с ними путь от скромного происхождения до великого предназначения, за это время они обретут уникальные черты, столкнутся со множеством испытаний и станут способными на настоящие подвиги. Каждый игрок получит своего героя с уникальной историей — но лишь одному суждено стать величайшим из них!
--------------------------------------------------------------------------------
[Chunk 3]
Компоненты 45 карт персонажа 15 карт происхождения • 15 карт стремления • 15 карт судьбы 91 карта истории 29 карт I-го акта • 32 карты II-го акта • 30 карт III-го акта 50 карт героев и антигероев 25 карты героев • 25 карты антигероев 12 карт для одиночного и кооперативного режимов 40 фишек опыта 4 планшета персонажей и 4 маркера героев 24 руны 3 руны силы • 3 руны ловкости 3 руны телосложения 3 руны интеллекта • 3 руны мудрости 3 руны обаяния • 3 основных руны • 3 руны Тьмы
--------------------------------------------------------------------------------
[Chunk 4]
Об игре Играя в «Дорогу приключений», вы пройдете три акта, полных испытаний и возможностей. Ваших героев ждут триумфы, трагедии и горечь поражений. Последние принесут с собой ценный опыт, распорядиться которым можно будет в будущих приключениях. С концом третьего акта игра завершится, а игрок, собравший больше всего очков судьбы, станет победителем!
--------------------------------------------------------------------------------
[Chunk 5]
Перед тем как начать игру, найдите достаточно свободного места, разложите игровые компоненты и перемешайте колоды. На этапе подготовки каждый игрок создает своего персонажа. 1. Раздайте карты Раздайте каждому игроку по 6 карт персонажа: • 2 карты происхождения (коричневые с бронзовой оковкой). 2 карты стремления (синие с серебряной оковкой). 2 карты судьбы (красные с золотой оковкой). Игроки оставляют себе по одной карте каждого типа, а остальные возвращают в коробку.
--------------------------------------------------------------------------------
[Chunk 6]
Если вы играете в первый раз, пропустите шаги выше и просто раздайте каждому игроку по одной карте каждого типа. Затем раздайте каждому игроку по три фишки опыта и одной карте героя, с которыми они начнут игру. Не показывайте карты героя и антигероя другим игрокам. 2. Создайте ваших персонажей Три карты персонажа, выбранные вами, образуют его историю.
--------------------------------------------------------------------------------
[Chunk 7]
Поместите их на планшет персонажа: карту происхождения — в левый столбец (лицом вверх), стремления — в средний (лицом вверх), а судьбы — в правый (лицом вниз, но вы можете посмотреть ее в любое время). В ходе игры история вашего персонажа станет богаче и обзаведется множеством деталей. Вот некоторые из них: Руны способностей, которыми вы сможете воспользоваться. Триумфы и трагедии, которые принесут вам очки в конце игры. Особые силы, указанные на картах персонажа, и знаки судьбы.
--------------------------------------------------------------------------------
[Chunk 8]
Особые силы, указанные на картах персонажа, и знаки судьбы. В левой части планшета персонажа находится шкала тьмы — она показывает, насколько ваш персонаж погряз во зле. В начале игры все персонажи находятся на грани между добром и злом: поместите ваш маркер героя на третье деление сверху. Когда вы совершаете (значок злого деяния), опустите маркер на одно деление вниз, а когда совершаете (значок доброго деяния), поднимите на одно деление вверх.
--------------------------------------------------------------------------------
[Chunk 9]
Шкала тьмы определяет, можете и бросать руны Тьмы, а также влияет на ваш результат ли вы разыгрывать из руки карты в конце игры. Пример: подготовка и планшет персонажа Получив шесть карт персонажа, Ксюша выбирает происхождение «Охотник», стремление честью» и тайную судьбу «Дитя природы». Она помещает выбранные карты на свой планшет персонажа и устанавливает маркер на начальное деление на шкале тьмы. Теперь она готова к игре! или
--------------------------------------------------------------------------------
[Chunk 10]
«Связанный 3. Подготовьте колоды истории Разместите в центре стола три колоды истории, колоду героя и колоду антигероя. Если вы играете в первый раз, советуем перед началом игры убрать из колод историй все карты союзников и карты злодеев (а также связанные с ними карты «Дворянин», «Выживший», «Клятва мщения», «Наследник престола», «Мастер над шпионами» и «Вероломное предательство») и добавить их в игру в последующих партиях. Рядом с каждой колодой истории выложите в ряд лицом вниз карты.
--------------------------------------------------------------------------------

## Добавление в векторную БД

Рассмотрим  multilingual-e5-small в качестве бейзлайна, в дальнейших в экспериментах посмотрим на другие модели

In [57]:
from qdrant_client import QdrantClient
from qdrant_client.http.models import VectorParams, Distance, PointStruct
from sentence_transformers import SentenceTransformer

qclient = QdrantClient(url="http://localhost:6333")

COLLECTION = "games_chunks_e5_small"

# multilingual-e5-small → 384d
qclient.recreate_collection(
    collection_name=COLLECTION,
    vectors_config=VectorParams(
        size=384,
        distance=Distance.COSINE
    )
)

model = SentenceTransformer("/Users/kapitolinakondakova/models/multilingual-e5-small")

/var/folders/kh/xsjpwqw577x7d3m333j9gb3h0000gn/T/ipykernel_32127/4159141748.py:10: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qclient.recreate_collection(
Loading weights: 100%|█| 199/199 [00:00<00:00, 854.93it/s, Materializing param=p
BertModel LOAD REPORT from: /Users/kapitolinakondakova/models/multilingual-e5-small
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [58]:
global_id = 0

def add_chunks(chunks_dict, chunking_type):
    global global_id
    points = []

    for game, chunks in tqdm(chunks_dict.items()):
        for text in chunks:
            text = text.strip()
            if not text:
                continue

            vector = model.encode(text, normalize_embeddings=True)

            points.append(
                PointStruct(
                    id=global_id,
                    vector=vector.tolist(),
                    payload={"game": game, "chunking": chunking_type, "text": text},
                )
            )
            global_id += 1

    qclient.upsert(collection_name=COLLECTION, points=points)


add_chunks(games_chunks_token, "token")
add_chunks(games_chunks_sentence, "sentence")
add_chunks(games_chunks_semantic, "semantic")
add_chunks(games_chunks_structure, "structure")

100%|█████████████████████████████████████████████| 9/9 [00:52<00:00,  5.82s/it]
100%|█████████████████████████████████████████████| 9/9 [00:56<00:00,  6.22s/it]
100%|█████████████████████████████████████████████| 9/9 [01:42<00:00, 11.40s/it]
100%|█████████████████████████████████████████████| 9/9 [01:10<00:00,  7.84s/it]

In [59]:
qclient.get_collections()
info = qclient.get_collection(COLLECTION)
print(info.points_count)

3756

In [70]:
import pandas as pd

df = pd.read_csv("ques.csv")
df = df.rename(columns={'игра': 'game', 'вопрос': 'question', 'ответ': 'answer'})
df.head()

,game,question,answer
0,Дюна: Империя,что такое карты интриг?,"Эти карты представляют специальные операции, т..."
1,Дюна: Империя,считается ли дредноут боевой силой?,"Дредноуты. Правила базовой игры требуют, чтобы..."
2,Дюна: Империя,дом хагаль может помещать жетон контроля?,Поскольку Дом Хагаль не получает награды за уч...
3,Дюна: Империя,я могу несколько раз отправится в высший совет?,Высший Совет\nСимвол агента: Ландсраад Стоимос...
4,Взрывные котята,что делает карта «Подсмуртри грядущее»?,"Посмотри 3 верхние карты колоды, не показывая ..."

In [94]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from qdrant_client.http.models import Filter, FieldCondition, MatchValue

# НАСТРОЙКИ

COLLECTION = "games_chunks_e5_small"
METHODS = ["token", "sentence", "semantic", "structure"]
TOP_K = 5
COVERAGE_THRESHOLD = 0.95


# ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ

import re

def normalize_tokens(text: str) -> set[str]:
    return set(
        re.findall(r"\w+", text.lower(), flags=re.UNICODE)
    )

def answer_coverage(answer: str, chunk: str) -> float:
    """
    Доля токенов ответа, содержащихся в чанке
    """
    ans_tokens = normalize_tokens(answer)
    if not ans_tokens:
        return 0.0

    chunk_tokens = normalize_tokens(chunk)
    return len(ans_tokens & chunk_tokens) / len(ans_tokens)

def search_top5_chunks(game: str, question: str, chunking: str) -> list[str]:
    """Ищет TOP_K чанков в Qdrant для заданной игры и метода чанкинга"""
    qvec = model.encode(question, normalize_embeddings=True).tolist()

    res = qclient.query_points(
        collection_name=COLLECTION,
        query=qvec,
        limit=TOP_K,
        query_filter=Filter(
            must=[
                FieldCondition(key="game", match=MatchValue(value=game)),
                FieldCondition(key="chunking", match=MatchValue(value=chunking)),
            ]
        ),
        with_payload=True,
    )

    texts = [
        (hit.payload or {}).get("text", "") or ""
        for hit in res.points
    ]

    # гарантируем длину TOP_K
    while len(texts) < TOP_K:
        texts.append("")

    return texts


# ОЦЕНКА ОДНОГО МЕТОДА

def eval_one_method(
    df: pd.DataFrame,
    method: str,
) -> pd.DataFrame:

    out = df.copy()

    # столбцы для текстов чанков
    for i in range(1, TOP_K + 1):
        out[f"{method}_top{i}"] = ""

    # метрики
    out[f"{method}_hit5"] = 0
    out[f"{method}_mrr"] = 0.0
    out[f"{method}_hit1"] = 0
    out[f"{method}_coverage@1"] = 0.0

    for idx, row in tqdm(out.iterrows(), total=len(out), desc=f"Eval {method}"):

        game = row["game"]
        question = row["question"]

        top_texts = search_top5_chunks(game, question, method)

        # сохраняем тексты
        for i, t in enumerate(top_texts, start=1):
            out.at[idx, f"{method}_top{i}"] = t

        gold_text = row["answer"]

        sims = []
        for t in top_texts:
            if not t.strip():
                sims.append(0.0)
                continue
            sims.append(answer_coverage(gold_text, t))

        out.at[idx, f"{method}_hit5"] = int(any(s >= COVERAGE_THRESHOLD for s in sims))

        out.at[idx, f"{method}_hit1"] = int(sims[0] >= COVERAGE_THRESHOLD)
        out.at[idx, f"{method}_coverage@1"] = sims[0]

        rr = 0.0
        for rank, s in enumerate(sims, start=1):
            if s >= COVERAGE_THRESHOLD:
                rr = 1.0 / rank
                break
        out.at[idx, f"{method}_mrr"] = rr

    return out


def add_metrics_and_top5(df: pd.DataFrame) -> pd.DataFrame:
    """
    df: колонки ["game", "question", "answer"]
    """

    res = df.copy()
    for method in METHODS:
        res = eval_one_method(res, method)

    return res


df_scored = add_metrics_and_top5(df)


summary = {}
for m in METHODS:
    summary[m] = {
        "Hit@1": float(df_scored[f"{m}_hit1"].mean()),
        "Hit@5": float(df_scored[f"{m}_hit5"].mean()),
        "MRR@5": float(df_scored[f"{m}_mrr"].mean()),
        "MeanCoverage@1": float(df_scored[f"{m}_coverage@1"].mean()),
    }

summary_df = pd.DataFrame(summary).T
print(summary_df)

Eval token: 100%|███████████████████████████████| 24/24 [00:03<00:00,  6.86it/s]
Eval sentence: 100%|████████████████████████████| 24/24 [00:01<00:00, 18.43it/s]
Eval semantic: 100%|████████████████████████████| 24/24 [00:01<00:00, 21.51it/s]
Eval structure: 100%|███████████████████████████| 24/24 [00:01<00:00, 18.25it/s]

              Hit@1     Hit@5     MRR@5  MeanCoverage@1
token      0.083333  0.333333  0.157639        0.503757
sentence   0.250000  0.541667  0.364583        0.539487
semantic   0.166667  0.250000  0.197917        0.400797
structure  0.166667  0.375000  0.243056        0.440340

In [87]:
df_scored

,game,question,answer,token_top1,token_top2,token_top3,token_top4,token_top5,token_hit5,token_mrr,...,semantic_mrr,semantic_hit1,structure_top1,structure_top2,structure_top3,structure_top4,structure_top5,structure_hit5,structure_mrr,structure_hit1
0,Дюна: Империя,что такое карты интриг?,"Эти карты представляют специальные операции, т...","ут вам получать ресурсы, увеличивать влияние в...","те просматривать их в любое время, но соперник...","ю карту и другими способами (например, «В обхо...",тый наблюдательный пункт рядом с любой ячейкой...,"батывает только при раскрытии карт (например, ...",1,1.000000,...,0.333333,0,ФракЦИИ\nкарты ИнтрИг\nЭти карты представляют ...,1 карта интриги,"ФракЦИИ\nПолучив карты интриг, держите их лице...",www.direwolfdigital.com\nЗаказное убийство. Эф...,www.direwolfdigital.com\nВозьмите карту из кол...,1,1.000000,1
1,Дюна: Империя,считается ли дредноут боевой силой?,"Дредноуты. Правила базовой игры требуют, чтобы...","онфликта, чтобы вы могли играть карты сражения...",тя бы 1 ваш отряд. Если в зоне конфликта не ос...,"наград, поскольку не участвовал в сражении. Од...",Гхола. Если вы сращиваете «Гхолу» с «Грузолёто...,Третья награда (по такому же принципу) выдаётс...,1,1.000000,...,0.500000,0,www.direwolfdigital.com\nЕсли в зоне конфликта...,www.direwolfdigital.com\nДань победителю. См. ...,www.direwolfdigital.com\n12 правил пояснение к...,www.direwolfdigital.com\nПри использовании доп...,подсчёт боевой сИЛы\nПодсчитав свою боевую сил...,1,1.000000,1
2,Дюна: Империя,дом хагаль может помещать жетон контроля?,Поскольку Дом Хагаль не получает награды за уч...,"лучает награды за участие в сражении, он не по...","кубики составляют его запас, то есть Дом Хагал...","оков три агента, а у другого — два, то в одном...","ть игрокам, действуя по особым правилам. Он не...","ых других действий. Вы берёте карту, а затем м...",1,1.000000,...,1.000000,1,ПодготовкА к игре\nВыберите цвет для Дома Хага...,ПОДГОТОВКА К ИГРЕ\nВыберите цвет для Дома Хага...,www.direwolfdigital.com\nКонтроль. Если вы поб...,"ПОДГОТОВКА К ИГРЕ\nОднако, если он побеждает в...",ПОДГОТОВКА К ИГРЕ\nЖетон первого игрока получа...,1,1.000000,1
3,Дюна: Империя,я могу несколько раз отправится в высший совет?,Высший Совет\nСимвол агента: Ландсраад Стоимос...,", вы должны выполнить её условия и заплатить е...","тов. Вы просто отправляете агента, уже находящ...",отряда.\nЗаключение контракта Символ агента: Т...,количество новых отрядов.\nСолярии (валюту Имп...,ожете отправить агента в эту ячейку только оди...,1,0.333333,...,0.250000,0,"www.direwolfdigital.com\nНапример, вы должны з...",www.direwolfdigital.com\nПланы внутри планов. ...,www.direwolfdigital.com\nЛожные приказы. Кажды...,Справочник ячеек на игровом поле\nВеликая Равн...,Размещение отрядов в зоне конфликта\nВы можете...,1,0.250000,0
4,Взрывные котята,что делает карта «Подсмуртри грядущее»?,"Посмотри 3 верхние карты колоды, не показывая ...",ичество карт на руке не ограничено. Если у теб...,"Неть»-карту, которая отменяет действие твоей к...",то действие было отменено «Неть»-картой).\nПод...,дителем! можешь залить всех сиянием собственно...,Следующий за тобой игрок должен со- вершить 2 ...,0,0.000000,...,0.000000,0,Конец игры\nКоличество карт на руке не огранич...,и у ТЕБЯ пригорит от злости и обиды. не взорвё...,5 разных карт Если ты сыграешь в качестве особ...,Хочу подсмуртреть грядущее!\nТщательно перемеш...,Так ты останешься жив.\nТактический совет: пос...,0,0.000000,0
5,Взрывные котята,"что будет, если я возьму взрывного котенка?",Немедленно покажи эту карту. Если у тебя нет «...,"ыграй, затем бери.\nКонец игры\nПобеждает игро...",й ход участник играет карты с руки (по желанию...,рты. В свой первый ход он сам играет карту «На...,ичество карт на руке не ограничено. Если у теб...,"именив свойство одной карты, ты можешь сыграть...",1,0.250000,...,1.000000,1,Хочу подсмуртреть грядущее!\nТщательно перемеш...,"Конец игры\nПобеждает игрок, не взорвавшийся н...",Конец игры\nНападай (2х) 4 карты\nвзрывной кот...,Конец игры\nТеперь для этого ты можешь сыграть...,Конец игры\nКоличество карт на руке не огранич...,1,0.500000,0
6,Трамвай смерти,куда я могу положить карту секретов,"Если у вас в руке\nесть карты секретов,\nвыбер...","Он может посмотреть их, но показывать даже чле...",ерсонажа. Если у вас в руке есть карты секрето...,ых не жалко задавить.\n175 карт секретов — мог...,"те поле так, чтобы сторона с един- ственным пу...","кретов. Каждый игрок в команде, начиная с четв...",1,0.500000,...,0.500000,0,Как играть подробно\nКоманда соперников делает...,Объясняется за 2 минуты\nТут стоит воображаемы...,"Тот, кто издевался над вами в детстве\nДля пут...","Тот, кто издевался над вами в детстве\nОстальн...",Как играть подробно\nОстальные убирает в короб...,1,1.000000,1
7,Трамвай смерти,кто побеждает в игре?,"Посчитайте, сколько жетонов смерти у каждого ...","дой и играют за второй путь. Сделайте так, что...",т читать мелкий текст — давайте играть!\nexplo...,Затем кладёт на свой путь одного добряка по св...,"брал меньше всех!\nЕсли ничья, то просто верни...","грает за второй путь.\nДима, Женя\nАня\nБоря, ...",0,0.000000,...,1.000000,1,3–13 игроков,Боевик «Аль-Каиды»\nНачните новый круг по тем ...,Боевик «Аль-Каиды»\nПоверните игровое поле так...,"Тот, кто издевался над вами в детстве\nДля пут...",Как играть подробно\n1.\nСначала вы по очереди...,1,0.500000,0
8,Игра престолов,что делать если закончились жетоны,"Число отрядов, жетонов и карт в распоряжении к...",Отбой\nБой завершён. Снимите с поля приказ пох...,юбой момент игры дарить друг другу жетоны влас...,жетон приказа Же- лезного банка (см. «Морские ...,ление по треку одичалых (за раунд жетон может ...,"е пройдёт весь круг ходов, прежде чем до позиц...",0,0.000000,...,0.000000,0,"Последствия\nЭто происходит, когда и жетон угр...",Другие правила отступления\nЕсли в бою победил...,Знак одичалых\nПри победе одичалых жетон отсту...,Жетон приказа Железного банка,СПИСОК ИСПРАВЛЕНИЙ В ПРАВИЛАХ\nЖетоны приказов...,0,0.000000,0
9,Игра престолов,можно ли использовать эссос если таргариены не...,"Поле Эссоса используется, толь- ко если один и...",остранство расширится: доба- вятся новые земли...,"частвуют в партии, только если игроков четверо...","л Таргариенов в качестве игрового дома, уберит...",олнением «Мать драконов» втроём или вчетвером ...,жить можно только один.\nВ: при розыгрыше карт...,1,1.000000,...,1.000000,1,Дом Таргариенов: если дом Таргариенов принима-...,Дом Таргариенов: если дом Таргариенов принимае...,Другие правила вассалов\nДом Таргариенов начин...,Дом Таргариенов: если дом Таргариенов принима-...,ДОПОЛНЕНИЯ\nВ: поскольку у Таргариенов нет оса...,1,1.000000,1
10,Игра престолов,проигравший может выбрать осадную башню в каче...,О: нет. Осадные башни автоматически уничтожают...,одмоги. Как написано на стр. 20 буклета правил...,ить осадную башню?\nО: Таргариен игнорирует эт...,е помогает ситуации) против двух рыцарей высто...,когда жетон верности помещается или передвига-...,"грок разыграл приказ похода, вывел с его помощ...",0,0.000000,...,0.333333,0,свой поход;\nБой и движение отрядов В: когда п...,ДОПОЛНЕНИЯ\nВ: поскольку у Таргариенов нет оса...,Другие правила отступления\nɇ Игрок может испо...,могу защищающемуся;\nЕсть ли у игроков возможн...,Последствия\nКак и в большинстве прочих игровы...,1,1.000000,1
11,Дорога приключений,как купить черту,"Вы можете приобрести черту, если выполните все...",взять себе черту характера или пройти испытани...,". Когда вы берете карту черты, поместите ее по...",вверх.\nПоставьте рядом органайзер с основными...,вашей истории (см. стр. 5).\nпроисхождения и с...,"дет, если я опущусь в самый низ шкалы Тьмы?\nС...",1,1.000000,...,1.000000,1,"карте\nНапример, потратить очки опыта или разы...",Памятка\nВаш ход На вашем ходу вы можете взять...,«Связанный\n(Подробнее о рунах можно прочесть ...,Если у меня выпал символ\nЕсли другой игрок от...,Благодарности\nМы также благодарим всех плейте...,1,1.000000,1
12,Дорога приключений,что значит отправиться в странствие,Отправиться в странствие — один раз за ход вы ...,"ред тем как отважиться на испытание, вы должны...",чтобы сбросить любую открытую карту любого акт...,"исхождения есть всего две карты, вы обязаны по...","оку 2 карты происхождения, 2 карты стремления ...","и ваш персонаж вы полняет условия, (подробнее ...",1,1.000000,...,1.000000,1,карте\nОтправиться в странствие — один раз за ...,"карте\nПеред тем как отважиться на испытание, ...",Благодарности\nВыложите выбранные карты\n3. Вы...,Сочетание рун,Мудрость,1,1.000000,1
13,Дорога приключений,что дают значки на карточках,В процессе игры ваш герой может быть отмечен ...,", они делят победу.\nНо это еще не все: после ...",ои значки Природы она получает еще 4 очка триу...,те карту союзника под выбранную карту испытани...,"и у меня выпал символ\nпри броске рун, когда я...",чтобы сбросить любую открытую карту любого акт...,1,0.500000,...,0.200000,0,карте\nКсюша помещает Для этого она тратит кар...,Дополнительные элементы\nЕсли вы играете уже н...,Дополнительные элементы\nСоюзников нельзя закр...,"Если у меня выпал символ\nЗатем, перед тем как...","Если у меня выпал символ\nпри броске рун, когд...",0,0.000000,0
14,Бункер,что делать после открытия карт?,"Когда круг завершён, переходите к Голосованию,...",ту Бункера – она может вам пригодиться. Продол...,я 3-я карта Бункера - Круг открытия карт: все ...,Соберите все карты Профессий персонажей в бунк...,твами открытых карт бункера.\n1. Попавшие в 1....,", но есть полезные персонажи: владельцы таких ...",0,0.000000,...,0.000000,0,I. Судьба попавших в бункер\n- если вы открыли...,ХОД ИГРЫ\nКарта даст вам новую информацию о бу...,I. Судьба попавших в бункер\nСоберите все карт...,I. Судьба попавших в бункер\nОткройте 2 случай...,ППОДГОТОВКА К ИГРЕ\nАргументируя свою полезнос...,0,0.000000,0
15,Бункер,"что делать тем, кто не попал в бункер?","Изгнанным персонажам, к счастью, удалось найти...",твами открытых карт бункера.\n1. Попавшие в 1....,Соберите все карты Профессий персонажей в бунк...,ь не нужно). Изгнанные игроки также раскрывают...,ные ещё неоткрытые персонажи погибают. Карты б...,п Игроки получают несколько карт характеристик...,1,1.000000,...,0.500000,0,I. Судьба попавших в бункер\nПопавшие в бункер...,I. Судьба попавших в бункер\nУчитывайте все ка...,I. Судьба попавших в бункер\nПродолжайте откры...,I. Судьба попавших в бункер\n- если вы открыли...,I. Судьба попавших в бункер\nПродолжайте откры...,1,1.000000,1
16,Карточные войны,можно флюпать карты на первом ходу?,Правило первого игрока: если ты первый игрок ...,"амый крутой из вас. Если это ваша первая игра,...",убодробительных правил!\nПорядок хода\nа т р а...,повёрнутые) существа должны нападать. Ты сам в...,"аться, если нападают на него. Если хочешь напа...","существ, строения и заклинания с руки. На боль...",0,0.000000,...,1.000000,1,Порядок хода\nа т р а к я а н н е л в о т о г ...,Порядок хода\nНа большинстве карт указан тип з...,Порядок хода\nЕсли хочешь напасть на соперника...,"Порядок хода\nТы сам выбираешь, в каком порядк...",Порядок хода\nОдно действие — одна карта. Если...,0,0.000000,0
17,Карточные войны,в чем принципиальное различие строений и существ?,"Отличие строения от существа в том, что строен...","замени его и, возможно, ты спасёшь свою шкуру!...",щество в зоне непосредственно слева или справа...,другое строение. Заменять существо или строе- ...,"я бы одно кукурузное поле.\nПотратив действия,...","ер, если у тебя одно кукурузное поле и три пер...",1,0.250000,...,0.250000,0,Строения\nЕсли напро- тив твоего существа нет ...,Строения\nРозыгрыш строений во многом похож на...,Строения\nСбросить карту: когда какой-то эффек...,Строения\nОсобая благодарность выражается Илье...,Строения\nПеремещение между зонами: существо и...,0,0.000000,0
18,Карточные войны,если мое существо умерло то оно может убить су...,"даже если существо погибает, оно всё равно нан...",земли перевёрнуты.\nСражения После того как ты...,"а напасть ему мешает крутой пёс, это существо ...",щество в зоне непосредственно слева или справа...,"о урона, полученного существом, превысило его ...","ничтожить любое существо под твоим контролем, ...",0,0.000000,...,0.000000,0,Порядок хода\nА если ты успел заменить существ...,Строения\nЕсли напро- тив твоего существа нет ...,Строения\nА если у соперника в зоне нет сущест...,"Порядок хода\nСделав это, ты применяешь способ...","Порядок хода\nК примеру, необязательно играть ...",1,0.500000,0
19,Каркассон,что я получу за незавершенные дороги,Владелец каждой незаверш ̧нной дороги получает...,когда к карте был присоедин¸н последний оставш...,"но необяза- тельно. Вы вправе не делать этого,...",й из них получает очки в полном объ¸ме.\nКак в...,данного в разбойника\nВыложив квадрат с дорого...,"льном подсч¸те очков каждый игрок, чей аббат н...",1,1.000000,...,0.333333,0,КОНЕЦ ИГРЫ И ФИНАЛЬНЫЙ ПОДСЧЕТ ОЧКОВ\nИгра зав...,"ХОД ИГРЫ\nВы вправе не делать этого, если не х...",…на одной дороге\nВ получившемся городе ваших ...,…на одной дороге\nНовым квадратом вы могли бы ...,Краткий обзор основных правил\nПодсч¸т очков\n...,1,1.000000,1
20,Каркассон,что делать с реками в дополнении,Игра вед ̧тся по правилам базового «Каркассона...,на одном поле может находится сразу несколько ...,"с квадратами с рекой, пока кто-то из игроков н...",", на которых изображены города и монастыри, по...","- вать в одну сторону, потому что река не долж...","исованными на них дорогами, городами, полями и...",1,1.000000,...,1.000000,1,Подготовка к игре\nЕсли вы играете с дополнени...,Состав дополнения\n12 квадратов с рекой (в игр...,СОСТАВ И ПОДГОТОВКА К ИГРЕ\nТакже в игре есть ...,СОСТАВ И ПОДГОТОВКА К ИГРЕ\nОбратная сторона у...,СОСТАВ И ПОДГОТОВКА К ИГРЕ\nЕсли игроков меньш...,1,1.000000,1
21,Каркассон,куда можно поставить поданного,"Размещайте подданного только на том квадрате, ...",данного в разбойника\nВыложив квадрат с дорого...,й из них получает очки в полном объ¸ме.\nКак в...,поста- вить в него фишку своего подданного из ...,"й квадрат выложить некуда, уберите его в короб...","а лю- бой объект, изображ¸нный на квадрате, ка...",1,0.250000,...,1.000000,1,Озеро\nВыставляем аббата или подданного\nВы мо...,Несколько подданных на одном объекте,ХОД ИГРЫ\nОн тут же становится разбойни- ком. ...,Монастыри\nКак превратить подданного в рыцаря\...,Источник,1,0.333333,0
22,Монополия Рик и Морти,что делать если я в долгах,Если Вы задолжали Банку или другому игроку бол...,"же порядке, в котором они покупались. Губл-кор...","зрастет, как показано на карточке собственника...","льше той суммы, которая у Вас имеется, Вы може...","циях флубл-ходули и губл- коробки, чтобы увели...",один ход (см. пункты 1-4). Внимание! Если дубл...,1,0.333333,...,1.000000,1,О Т Ч\n5: ЗАКЛАДЫВАЙТЕ ИМУЩЕСТВО Если у вас не...,"О Т Ч\nпункт Недвижимость, принадлежащая друго...",О Т Ч\nu Игрок становится банкротом и передает...,О Т Ч\nЕсли в локации присутствуют улучшения в...,"О Т Ч\nдоходы.\n5. Если у Вас выпадет дубль, п...",1,0.500000,0
23,Монополия Рик и Морти,как выбраться из тюрьмы,"Если вы попали в тюрьму, вам необходимо 1)\nис...",вует 3 способа выйти из тюрьмы: I Заплатите a5...,"же порядке, в котором они покупались. Губл-кор...",ТИЛИ) Не волнуйтесь! Если Вы остановитесь на п...,Передайте кубики следующему игроку! Кроме того...,"вы продаете коробку, вырученная сумма составля...",1,1.000000,...,0.500000,0,О Т Ч\n5: ЗАКЛАДЫВАЙТЕ ИМУЩЕСТВО Если у вас не...,О Т Ч\nII Используйте карточку Бесплатно освоб...,"3. Если вы попали в тюрьму, вам необходимо 1) ...",О Т Ч\n5: ОТПРАВЛЯЙТЕСЬ В ТЮРЬМУ Если Вы остан...,О Т Ч\nЕсли в дальнейшем Вы захотите выкупить ...,1,0.500000,0

In [98]:
def pretty_print_row(row: pd.Series):
    print("=" * 120)
    print(f"🎮 Игра: {row['game']}")
    print(f"❓ Вопрос:\n{row['question']}")
    print(f"✅ Эталонный ответ:\n{row['answer']}")
    print("=" * 120)

    for method in METHODS:
        print(f"\n🔹 Метод чанкинга: {method}")
        print(f"   Hit@1: {row[f'{method}_hit1']}")
        print(f"   Hit@5: {row[f'{method}_hit5']}")
        print(f"   MRR@5: {row[f'{method}_mrr']:.3f}")
        print(f"   Coverage@1: {row[f'{method}_coverage@1']:.3f}")

        print("   Топ-1 чанк")
        for i in range(1, 2):
            text = row[f"{method}_top{i}"]
            short = text
            print(f"     [{i}] {short}")

    print("\n" + "=" * 120)

In [99]:
pretty_print_row(df_scored.iloc[0])

========================================================================================================================
🎮 Игра: Дюна: Империя
❓ Вопрос:
что такое карты интриг?
✅ Эталонный ответ:
Эти карты представляют специальные операции, тайные договорённости и неожиданные повороты. В игре они помогут вам получать ресурсы, увеличивать влияние во фракциях или даже получать ПО. На каждой карте интриги указано, в какой фазе её можно разыграть, какие у неё условия розыгрыша и эффект.
========================================================================================================================

🔹 Метод чанкинга: token
   Hit@1: 0
   Hit@5: 0
   MRR@5: 0.000
   Coverage@1: 0.725
   Топ-1 чанк
     [1] ут вам получать ресурсы, увеличивать влияние во фракциях или даже получать ПО. На каждой карте интриги указано, в какой фазе её можно разыграть, какие у неё условия розыгрыша и эффект.
На поле есть три ячейки, позволяющие получать карты интриг: «Карфаг», «Сговор» и «Тайны». Кроме того, карты интриг можно получить за соответствующие символы на других картах. Получив карты интриг, держите их лицевой стороной вниз отдельно от своей колоды. Вы можете просматривать их в любое время, но сопернику такая карта раск

🔹 Метод чанкинга: sentence
   Hit@1: 1
   Hit@5: 1
   MRR@5: 1.000
   Coverage@1: 1.000
   Топ-1 чанк
     [1] Как только другой игрок поднимется выше на треке влияния этой фракции, он забирает этот жетон и получает 1 ПО, а игрок, у которого забрали жетон, это 1 ПО теряет.
карты ИнтрИг
Эти карты представляют специальные операции, тайные договорённости и неожиданные повороты. В игре они помогут вам получать ресурсы, увеличивать влияние во фракциях или даже получать ПО. На каждой карте интриги указано, в какой фазе её можно разыграть, какие у неё условия розыгрыша и эффект.

🔹 Метод чанкинга: semantic
   Hit@1: 0
   Hit@5: 0
   MRR@5: 0.000
   Coverage@1: 0.050
   Топ-1 чанк
     [1] также «Карты интриг».
Внедрение. Разыгрывая карту с символом внедрения для отправки агента, вы можете отправить агента в ячейку, уже занятую агентом соперника.

🔹 Метод чанкинга: structure
   Hit@1: 1
   Hit@5: 1
   MRR@5: 1.000
   Coverage@1: 1.000
   Топ-1 чанк
     [1] ФракЦИИ
карты ИнтрИг
Эти карты представляют специальные операции, тайные договорённости и неожиданные повороты. В игре они помогут вам получать ресурсы, увеличивать влияние во фракциях или даже получать ПО. На каждой карте интриги указано, в какой фазе её можно разыграть, какие у неё условия розыгрыша и эффект.
На поле есть три ячейки, позволяющие получать карты интриг: «Карфаг», «Сговор» и «Тайны». Кроме того, карты интриг можно получить за соответствующие символы на других картах.

========================================================================================================================